### DISCUSSION TITLE
How to set custom .deb dependencies for electron-vite app?

### DISCUSSION THREAD

**Discussion by BurnedScarecrow** [alex8088/electron-vite#320] [Q&A]
Hi! I try to set some additional dependency for a deb package.

Docs for electron-builder says it should be written in config file. So I found `electron-builder.yml` file and added there default dependencies like they mentioned in [debian-package-options](https://www.electron.build/configuration/linux#debian-package-options).

I paste it like an array appended with my extra dependency (let it be shadowsocks-libev):
```yml
# ...
linux:
  target:
    - AppImage
    - snap
    - deb
  maintainer: example.com
  category: Utility
deb:
  depends:
    - gconf2
    - gconf-service
    - libnotify4
    - libappindicator1
    - libxtst6
    - libnss3
    - shadowsocks-libev
# ...
```

After configuration for builder the command `npm run build:linux` works well without errors, but when i try to `sudo apt install ./electron-app_1.0.0_amd64.deb` it sais that this app needs only default for electron app dependencies without my extra deps. and installs without extra dependency installation.

So, how can i mention custom deps or enable installation of my custom dependencies for deb package?
