### DISCUSSION TITLE
关于外置配置文件的处理方式

### DISCUSSION THREAD

**Discussion by islet-recover** [alex8088/electron-vite#782] [Show and tell]
利用Electron构建了加载不同WEB系统页面的应用，为了方便打包后修改系统页面地址进行调试，需要添加一个配置文件，我的解决方案是：
1、在根目录创建config.yaml:

     ```
      web1:
        dev: http://***
        prod: http://***
      web2:
        dev:http://***
        prod: http://***
    ```

2、在packages.json中添加：

      ```
      "build": {
          ...
          "extraResources": [
            {
              "from": "config.yaml",
              "to": "."
            }
          ]
        }
    ```
3、在electron-builder.yaml中添加：

        ```
        files:
          - 'config.yaml'
      ```

4、在主进程

      ```
        import YAML from 'yaml'

      const appConfig = !app.isPackaged
        ? YAML.parse(readFileSync(join(__dirname, '../../config.yaml'), 'utf-8'))
        : YAML.parse(readFileSync(join(process.resourcesPath, 'config.yaml'), 'utf-8'))
      
      // 配置URL
      export const WEB1 = !app.isPackaged ? appConfig.main.dev : appConfig.main.prod
      export const WEB2 = !app.isPackaged ? appConfig.im.dev : appConfig.im.prod
      ```

打包后可在Resources/config.yaml中修改prod地址，重启应用后即生效
