### ISSUE TITLE
Add to the documentation: CI & CD configuration

### ISSUE THREAD

**Issue by jinsuichen** [alex8088/electron-vite#108]
### Clear and concise description of the problem

If possible, I suggest adding CI and CD related configuration to the documentation.  Take GitHub Actions for example, if we add workflows' basic configuration content, users can use CI & CD more easily and standardized.

### Suggested solution

For CI, we can add eslint configuration to format the code. Also, we can add configuration related to testing (but this brings us to another issue: adding testing feature to electron-vite). 

For CD, we can add automated binary compilation using multiple platforms and automatic release of GitHub Releases.

### Validations

- [x] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
Good suggestion!

**Comment by jinsuichen** [comment]
This is the solution I used for the CD, it may need further refinement somewhere. I think there is a way to combine the three "npm run build:xxx" statements into one sentence, and after reading the electron-builder documentation I think "electron-builder -p never" is a solution, but I'm not sure if this is correct. Hopefully this configuration will provide some reference value.

```yml
name: CD

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js
        uses: actions/setup-node@v3.0.0
        with:
          node-version: "16"

      - name: Install Dependencies
        run: npm install

      - name: build-linux
        if: matrix.os == 'ubuntu-latest'
        run: npm run build:linux

      - name: build-mac
        if: matrix.os == 'macos-latest'
        run: npm run build:mac

      - name: build-win
        if: matrix.os == 'windows-latest'
        run: npm run build:win

      - name: release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            dist/*.exe
            dist/*.zip
            dist/*.dmg
            dist/*.AppImage
            dist/*.snap
            dist/*.deb
            dist/*.rpm
            dist/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
```
