### ISSUE TITLE
打包后在部分windows10平台会闪退

### ISSUE THREAD

**Issue by nanwangjkl** [alex8088/electron-vite#214]
### Describe the bug

查看dmp文件显示为STATUS_BREAKPOINT(0x80000003)错误，用vite-plugin-electron构建的则正常
electron-builder.yaml如下
```yaml
directories:
  buildResources: build
files:
  - '!**/.vscode/*'
  - '!src/*'
  - '!electron.vite.config.{js,ts,mjs,cjs}'
  - '!{.eslintignore,.eslintrc.cjs,.prettierignore,.prettierrc.yaml,dev-app-update.yml,CHANGELOG.md,README.md}'
  - '!{.env,.env.*,.npmrc,pnpm-lock.yaml}'
asarUnpack:
  - resources/**
afterSign: build/notarize.js
win:
  executableName: minigame-script-xddq
  requestedExecutionLevel: requireAdministrator
  target:
    - target: portable
      arch: ia32

portable: 
  requestExecutionLevel: admin
nsis:
  artifactName: ${name}-${version}-setup.${ext}
  shortcutName: ${productName}
  uninstallDisplayName: ${productName}
  createDesktopShortcut: always
mac:
  entitlementsInherit: build/entitlements.mac.plist
  extendInfo:
    - NSCameraUsageDescription: Application requests access to the device's camera.
    - NSMicrophoneUsageDescription: Application requests access to the device's microphone.
    - NSDocumentsFolderUsageDescription: Application requests access to the user's Documents folder.
    - NSDownloadsFolderUsageDescription: Application requests access to the user's Downloads folder.
dmg:
  artifactName: ${name}-${version}.${ext}
linux:
  target:
    - AppImage
    - snap
    - deb
  maintainer: electronjs.org
  category: Utility
appImage:
  artifactName: ${name}-${version}.${ext}
npmRebuild: false
publish:
  provider: generic
  url: https://example.com/auto-updates
```
package.json如下
```json
{
  "dependencies": {
    "@electron-toolkit/preload": "^2.0.0",
    "@electron-toolkit/utils": "^1.0.2",
    "electron-updater": "^5.3.0",
    "winax": "^3.3.7"
  },
  "devDependencies": {
    "@electron/notarize": "^1.2.3",
    "bootstrap": "^5.3.0",
    "electron": "^24.4.1",
    "electron-builder": "^23.6.0",
    "electron-vite": "^1.0.23",
    "prettier": "^2.8.8",
    "sass": "^1.63.6",
    "solid-js": "^1.7.6",
    "standard": "^17.1.0",
    "vite": "^4.3.9",
    "vite-plugin-solid": "^2.7.0"
  }
}
```

### Electron-Vite Version

1.0.23

### Electron Version

24.4.1

### Vite Version

4.3.9

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.
