### ISSUE TITLE
CI/CD Github Action build fail

### ISSUE THREAD

**Issue by vicheanath** [alex8088/electron-vite#356]
### Describe the bug

```sh
✓ built in 3.44s
  • electron-builder  version=24.9.1 os=6.2.0-1018-azure
  • artifacts will be published  reason=tag is defined tag=v1.0.0-beta
  • loaded configuration  file=/home/runner/work/chuonnath/chuonnath/electron-builder.yml
  • skipped dependencies rebuild  reason=npmRebuild is set to false
  • packaging       platform=linux arch=x64 electron=28.0.0 appOutDir=dist/linux-unpacked
  • downloading     url=https://npmmirror.com/mirrors/electron/28.0.0/electron-v28.0.0-linux-x64.zip size=102 MB parts=8
  • downloaded      url=https://npmmirror.com/mirrors/electron/28.0.0/electron-v28.0.0-linux-x64.zip duration=2.851s
  • building        target=AppImage arch=x64 file=dist/chuonnath-1.0.0.AppImage
  • building        target=snap arch=x64 file=dist/chuonnath_1.0.0_amd64.snap
  • downloading     url=https://github.com/electron-userland/electron-builder-binaries/releases/download/snap-template-4.0-2/snap-template-electron-4.0-2-amd64.tar.7z size=1.5 MB parts=1
  • downloading     url=https://github.com/electron-userland/electron-builder-binaries/releases/download/appimage-12.0.1/appimage-12.0.1.7z size=1.6 MB parts=1
  • downloaded      url=https://github.com/electron-userland/electron-builder-binaries/releases/download/snap-template-4.0-2/snap-template-electron-4.0-2-amd64.tar.7z duration=204ms
  • downloaded      url=https://github.com/electron-userland/electron-builder-binaries/releases/download/appimage-12.0.1/appimage-12.0.1.7z duration=220ms
  • downloading     url=https://github.com/electron-userland/electron-builder-binaries/releases/download/appimage-12.0.1/appimage-12.0.1.7z size=1.6 MB parts=1
  • downloaded      url=https://github.com/electron-userland/electron-builder-binaries/releases/download/appimage-12.0.1/appimage-12.0.1.7z duration=1[44](https://github.com/vicheanath/chuonnath/actions/runs/7267260588/job/19800831290#step:5:45)ms
  • cannot move downloaded into final location (another process downloaded faster?)  path=/home/runner/.cache/electron-builder/appimage/appimage-12.0.1
                                                                                     tempFile=/home/runner/.cache/electron-builder/appimage/861474900
                                                                                     error=rename /home/runner/.cache/electron-builder/appimage/861474900 /home/runner/.cache/electron-builder/appimage/appimage-12.0.1: file exists
  • publishing      publisher=Snap Store
  • uploading       file=chuonnath_1.0.0_amd64.snap provider=snapStore
  • building        target=deb arch=x64 file=dist/chuonnath_1.0.0_amd64.deb
  • adding autoupdate files for: deb. (Beta feature)  resourceDir=/home/runner/work/chuonnath/chuonnath/dist/linux-unpacked/resources
  ⨯ snapcraft is not installed, please: sudo snap install snapcraft --classic  
  • downloading     url=https://github.com/electron-userland/electron-builder-binaries/releases/download/fpm-1.9.3-2.3.1-linux-x86_64/fpm-1.9.3-2.3.1-linux-x86_64.7z size=5.0 MB parts=1
  • downloaded      url=https://github.com/electron-userland/electron-builder-binaries/releases/download/fpm-1.9.3-2.3.1-linux-x86_64/fpm-1.9.3-2.3.1-linux-x86_64.7z duration=251ms
  ⨯ /home/runner/work/chuonnath/chuonnath/node_modules/app-builder-bin/linux/x64/app-builder process failed ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
Exit code:
1  failedTask=build stackTrace=Error: /home/runner/work/chuonnath/chuonnath/node_modules/app-builder-bin/linux/x64/app-builder process failed ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
Exit code:
1
    at ChildProcess.<anonymous> (/home/runner/work/chuonnath/chuonnath/node_modules/builder-util/src/util.ts:251:14)
    at Object.onceWrapper (node:events:628:26)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Socket.<anonymous> (node:internal/child_process:[45](https://github.com/vicheanath/chuonnath/actions/runs/7267260588/job/19800831290#step:5:46)8:11)
    at Socket.emit (node:events:[51](https://github.com/vicheanath/chuonnath/actions/runs/7267260588/job/19800831290#step:5:52)3:28)
    at Pipe.<anonymous> (node:net:301:12)
Error: The operation was canceled.
```

### Electron-Vite Version

1.0.27

### Electron Version

28.0.0

### Vite Version

4.4.9

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by vicheanath** [comment]
here is my `release.yml`

```yml
name: Build/release Electron app

on:
  push:
    tags:
      - v*.*.*

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install

      - name: build-linux
        if: matrix.os == 'ubuntu-latest'
        run: npm run build:linux

      - name: build-mac
        if: matrix.os == 'macos-latest'
        run: npm run build:mac

      - name: build-win
        if: matrix.os == 'windows-latest'
        run: npm run build:win

      - name: release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            dist/*.exe
            dist/*.zip
            dist/*.dmg
            dist/*.AppImage
            dist/*.snap
            dist/*.deb
            dist/*.rpm
            dist/*.tar.gz
            dist/*.yml
            dist/*.blockmap
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

```
