### ISSUE TITLE
cannot find module electron-store

### ISSUE THREAD

**Issue by dooonabe** [alex8088/electron-vite#540]
### Describe the bug

1. 一开始用的pnpm，然后按照文档增加了shamefully-hoist，重新install，报错
2. 后来换成了npm，还是一样的报错
3. 但是debugger模式下，服务可以正常启动

报错详细信息：
![微信截图_20240619182959](https://github.com/alex8088/electron-vite/assets/20391922/33cfdc2b-fa34-4914-8548-74bdeab35b42)

我的配置文件
1. electron.vite.config.ts
```ts

import { resolve } from 'path';
import {
  defineConfig,
  bytecodePlugin,
  externalizeDepsPlugin,
} from 'electron-vite';
import react from '@vitejs/plugin-react';

export default defineConfig({
  main: {
    plugins: [externalizeDepsPlugin(), bytecodePlugin()],
    build: {
      outDir: 'release/app/dist/main',
    },
  },
  preload: {
    plugins: [bytecodePlugin()],
    build: {
      lib: {
        entry: resolve(__dirname, './src/main/preload.ts'),
      },
      outDir: 'release/app/dist/preload',
    },
  },
  renderer: {
    resolve: {
      alias: {
        '@renderer': resolve('src/renderer'),
      },
    },
    build: {
      outDir: 'release/app/dist/renderer',
    },
    plugins: [react()],
  },
});

```

2.electron-builder.yml
```yml
appId: org.99tech.aics
productName: AI客服
asar: true
asarUnpack: "**\\*.{node,dll}"
compression: maximum
files:
  - dist
  - node_modules
  - package.json
  - '!**/.vscode/*'
  - '!src/*'
  - '!electron.vite.config.{js,ts,mjs,cjs}'
  - '!{.eslintignore,.eslintrc.cjs,.prettierignore,.prettierrc.yaml,dev-app-update.yml,CHANGELOG.md,README.md}'
  - '!{.env,.env.*,.npmrc,pnpm-lock.yaml,tsconfig.json,tsconfig.node.json,tsconfig.web.json}'
afterSign: '.erb/scripts/notarize.js'
win:
  requestedExecutionLevel: requireAdministrator
  target:
    - nsis
nsis:
  oneClick: false
  perMachine: true
  allowElevation: true
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
  shortcutName: AI客服
  uninstallDisplayName: aics
  deleteAppDataOnUninstall: true
  artifactName: '${productName} ${version}.${ext}'
directories:
  app: release/app
  buildResources: assets
  output: release/build
extraResources:
  - './assets/**'
afterPack: './removeLocales.js'

```
3. 项目结构
![image](https://github.com/alex8088/electron-vite/assets/20391922/3ca1b28e-fd3f-41ca-b280-58b01e6cf3a8)

4.electron-store引用
![image](https://github.com/alex8088/electron-vite/assets/20391922/18101cba-75ac-4059-992b-150def02fe9b)

大佬能帮忙看看是哪的问题吗

### Electron-Vite Version

2.2.0

### Electron Version

26.2.1

### Vite Version

4.4.11

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by dooonabe** [comment]
electron-store依赖在dependencies下

**Comment by alex8088** [comment]
请确保删除node_module和lock文件，再重新install。只是install是没有用的，其次是确保你的npmrc文件是生效的。

**Comment by dooonabe** [comment]
```对于主进程和预加载脚本，最佳实践是将依赖项外部化，只打包自己的代码。```
外部化的意思只是，将依赖打包到 app.asar 文件里面的node_modules目录下？

**Comment by alex8088** [comment]
包缺少和electron-vite无关，这是electron-builder没有将其打包， 而 webpack 是全量打包的模式，即将你引用的所有包重新打包一遍。e

exclude 就是将 electron-store 重新打包，至于你提到另外的报错，大致都是引用关系问题导致，没有具体信息无从判断。

**Comment by alex8088** [comment]
> `对于主进程和预加载脚本，最佳实践是将依赖项外部化，只打包自己的代码。` 外部化的意思只是，将依赖打包到 app.asar 文件里面的node_modules目录下？

和asar 没有关系。外部化就是将你使用的依赖包当成外部的模块，通常不需要在去编译他们，只需要编译自己的代码，只有但模块无法支持electron时如只支持esm的模块，才需要去编译它让它支持electron，externalizedep插件就是这个作用。

**Comment by alex8088** [comment]
你可以查找你的asar中到底有没有electron-store。

**Comment by alex8088** [comment]
你是否在electron-builder中配置排除所有的node_module

**Comment by dooonabe** [comment]
感谢大佬指点，我在electron-builder.yml发现重新指定了node_module目录，没有用工程根目录下的node_module
```yml
directories:
  app: release/app
  buildResources: assets
  output: release/build
```
