### ISSUE TITLE
在主进程中运行exe，在开发阶段可以正常运行，打包后运行失败

### ISSUE THREAD

**Issue by laddish** [alex8088/electron-vite#65]
### Describe the bug

# 需要在启动 electron 时调用另一个运行程序来开启一个后台服务

使用的是https://github.com/alex8088/electron-vite-boilerplate 模版创建的项目
以下是涉及到启动另一个应用程序相关的代码操作

## 目录结构
exe 可执行文件路径在项目根路径下 A 文件夹下的 A.exe，A文件夹下有 exe启动时 需要的各种 dll。
项目/
├─ A/
│  ├─ A.exe
│  ├─ 各种dll
├─ src/
│  ├─ main/
│  │  ├─ index.ts
├─ electron-builder.yml

## main/index.ts 执行 exe 的代码：
```ts
import { stat } from 'fs'
import { execFile } from 'child_process'
//根据exe路径执行exe
function startExe(path: string) {
  execFile(path,
    // parameters,
    (err, data) => {
      console.warn('Start Exe path: ',  path)
      if (err) {
        console.warn('Failed start Exe ')
        console.error(err)
      }
      else {
        console.warn('Start Exe successfully.', data.toString())
      }
    })
}
// 获取开发时的exe路径
const EXE_PATH = join(__dirname, '../../A/A.exe')

// 启动本地exe
function setupExe() {
  // 获取打包后的exe路径
  const packedExePath = join(process.cwd(), '/resources/A/A.exe')
  // 判断路径是否存在
  stat(TESLA_PATH, (err) => {
  //在开发阶段exe存在执行EXE_PATH，在打包后EXE_PATH不存在执行packedExePath 
    if (err)
      startExe(packedExePath)
    else
      startExe(EXE_PATH)
  },
  )
}

setupExe()
```

## electron-builder.yml 
相较模版主要加了extraResources这个选项，把A文件夹下的所有文件都拷贝到打包后的resources下的A文件夹下。
```yml
appId: com.electron.app
productName: electron-app
directories:
  buildResources: build
extraResources:
  from: A
  to: A
files:
  - '!**/.vscode/*'
  - '!src/*'
  - '!electron.vite.config.{js,ts,mjs,cjs}'
  - '!{.eslintignore,.eslintrc.cjs,.prettierignore,.prettierrc.yaml,dev-app-update.yml,CHANGELOG.md,README.md}'
  - '!{tsconfig.json,tsconfig.node.json,tsconfig.web.json}'
asarUnpack:
  - '**/*.{node,dll}'
afterSign: build/notarize.js
win:
  executableName: electron-app
nsis:
  artifactName: ${name}-${version}-setup.${ext}
  shortcutName: ${productName}
  uninstallDisplayName: ${productName}
  createDesktopShortcut: always
mac:
  entitlementsInherit: build/entitlements.mac.plist
  extendInfo:
    - NSCameraUsageDescription: Application requests access to the device's camera.
    - NSMicrophoneUsageDescription: Application requests access to the device's microphone.
    - NSDocumentsFolderUsageDescription: Application requests access to the user's Documents folder.
    - NSDownloadsFolderUsageDescription: Application requests access to the user's Downloads folder.
dmg:
  artifactName: ${name}-${version}.${ext}
linux:
  target:
    - AppImage
    - snap
    - deb
  maintainer: electronjs.org
  category: Utility
appImage:
  artifactName: ${name}-${version}.${ext}
npmRebuild: false
publish:
  provider: generic
  url: https://example.com/auto-updates

```

## 实际结果
以上这些操作，在开发阶段都可以正常运行。

但是在打包后启动时exe却启动不起来，

打印的路径为
```ts
setupExe  packedExePath D:\Electron\electron-vite-boilerplate\dist\win-unpacked\resources\A\A.exe
Start Exe path:  D:\Electron\electron-vite-boilerplate\dist\win-unpacked\resources\app.asar\A\A.exe
```

我在代码中获取的路径是这样拼接的
```ts
  // 获取打包后的exe路径
  const packedExePath = join(process.cwd(), '/resources/A/A.exe')
```

经过对比，

拼接的路径是正常的，但是在execFIle执行的时候

resources和A中间多了一个层级 app.asar。

注：
ASAR 加密： 将 Electron ASAR 文件进行加密，并修改 Electron 源代码，在读取 ASAR 文件之前对其解密后再运行。

![image](https://user-images.githubusercontent.com/49431692/205011810-8e7da9cc-3f14-4e6a-ad88-fb84d841e3d0.png)

## 期待的结果

我的疑问是 我需要如何做 才能避免这个多余的 app.asar 层级？

我尝试把
```yml
asarUnpack:
  - '**/*.{node,dll}'
```
改为
```yml
asar:
  false
```
关闭了 asar 加密可以在打包后正常调用起来exe，

但是我也尝试用其他开启了asar的社区模版，打包后可以正常调用起服务。

可以运行起来exe的electron-builder.json配置如下，可以看到里面 asar 是开启的，也可以调用其他的exe服务。
```json
{
  "appId": "YourAppID",
  "asar": true,
  "directories": {
    "output": "release/${version}"
  },
  "files": [
    "dist-electron",
    "dist"
  ],
  "mac": {
    "artifactName": "${productName}_${version}.${ext}",
    "target": [
      "dmg"
    ]
  },
  "win": {
    "target": [
      {
        "target": "nsis",
        "arch": [
          "x64"
        ]
      }
    ],
    "artifactName": "${productName}_${version}.${ext}"
  },
  "nsis": {
    "oneClick": false,
    "perMachine": false,
    "allowToChangeInstallationDirectory": true,
    "deleteAppDataOnUninstall": false
  }
}
```

### Electron-Vite Version

1.0.14

### Electron Version

21.3.0

### Vite Version

3.2.4

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.
